import {calc} from './calculations.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const N=['attendance','payments','settings'];
const db=await new Promise((ok,ko)=>{const q=indexedDB.open('workpay',1);q.onupgradeneeded=()=>N.forEach(n=>q.result.createObjectStore(n,{keyPath:'id'}));q.onsuccess=()=>ok(q.result);q.onerror=()=>ko(q.error)});
const rq=r=>new Promise((ok,ko)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>ko(r.error)});
const st=(s,m='readonly')=>db.transaction(s,m).objectStore(s);
const all=s=>rq(st(s).getAll()),put=(s,o)=>rq(st(s,'readwrite').put(o)),del=(s,id)=>rq(st(s,'readwrite').delete(id));
const bulk=(data,clear)=>{const t=db.transaction(N,'readwrite');N.forEach(n=>{const o=t.objectStore(n);if(clear)o.clear();(data[n]||[]).forEach(x=>o.put(x))});return new Promise((ok,ko)=>{t.oncomplete=ok;t.onerror=t.onabort=()=>ko(t.error)})};
const DEF={id:'default',payMode:'daily',dailyRate:255000,dailyRate13:450000,hourlyRate:35000,overtimeRate:39000,stdH:8,breakMin:60,interval:30,sched:'08:00:00',lateEnabled:true,shortRule:'prorate'};
const NUM=[['dailyRate','Lương ngày ca 8 tiếng'],['dailyRate13','Lương ngày ca 13 tiếng'],['hourlyRate','Lương giờ'],['overtimeRate','Tăng ca/giờ'],['stdH','Giờ công tiêu chuẩn'],['breakMin','Nghỉ (phút)'],['interval','Mốc đi trễ (phút)']];
const hourOptions=Array.from({length:24},(_,i)=>`<option value="${String(i).padStart(2,'0')}">${String(i).padStart(2,'0')}</option>`).join('');
const minuteOptions=Array.from({length:60},(_,i)=>`<option value="${String(i).padStart(2,'0')}">${String(i).padStart(2,'0')}</option>`).join('');
const timeControl=id=>`<div class="time-control"><select id="${id}_hour" aria-label="Giờ"><option value="">Giờ</option>${hourOptions}</select><span>:</span><select id="${id}_minute" aria-label="Phút"><option value="">Phút</option>${minuteOptions}</select></div>`;
const readTime=id=>{const h=$('#'+id+'_hour').value,m=$('#'+id+'_minute').value;return h&&m?`${h}:${m}:00`:''};
const setTime=(id,value)=>{const match=String(value||'').match(/^(\d{2}):(\d{2})/);$('#'+id+'_hour').value=match?match[1]:'';$('#'+id+'_minute').value=match?match[2]:''};
const fields=p=>`<label>Phương thức<select id=${p}payMode><option value=daily>Lương ngày</option><option value=hourly>Lương giờ</option></select></label>`+NUM.map(([k,l])=>`<label>${l}<input type=number step=any min=0 id=${p}${k}></label>`).join('')+`<label>Giờ bắt đầu theo lịch${timeControl(p+'sched')}</label><label><input type=checkbox id=${p}lateEnabled> Tính trễ/về sớm theo mốc</label><label>Thiếu giờ<select id=${p}shortRule><option value=prorate>Theo tỷ lệ</option><option value=full>Trả đủ ngày</option></select></label>`;
const keys=['payMode','sched','shortRule'];
const get=p=>({...Object.fromEntries(keys.map(k=>[k,k==='sched'?readTime(p+k):$('#'+p+k).value])),...Object.fromEntries(NUM.map(([k])=>[k,+$('#'+p+k).value])),lateEnabled:$('#'+p+'lateEnabled').checked});
const fill=(p,o)=>{keys.forEach(k=>k==='sched'?setTime(p+k,o[k]):$('#'+p+k).value=o[k]);NUM.forEach(([k])=>$('#'+p+k).value=o[k]);$('#'+p+'lateEnabled').checked=o.lateEnabled};
$('#sf').innerHTML=fields('s_');
const money=n=>Math.round(n||0).toLocaleString('vi-VN')+' ₫',hr=s=>((s||0)/3600).toFixed(2);
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh'}).format(new Date());
let S=DEF,recs=[],pays=[],ym=today.slice(0,7),year=+today.slice(0,4),cur=null;
const toast=(m)=>{const t=$('#toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',2500)};
async function load(){recs=await all('attendance');pays=await all('payments');S={...DEF,...((await all('settings')).find(x=>x.id==='default')||{})};render()}
const monthRecs=()=>recs.filter(r=>r.workDate.startsWith(ym)).sort((a,b)=>a.workDate<b.workDate?-1:1);
function render(){renderCal();renderPay();renderYear();fill('s_',S);conv()}
function renderCal(){const[y,m]=ym.split('-').map(Number);$('#ml').textContent=`Tháng ${m}/${y}`;const first=new Date(Date.UTC(y,m-1,1)),off=(first.getUTCDay()+6)%7;let h=['T2','T3','T4','T5','T6','T7','CN'].map(d=>`<div class=h>${d}</div>`).join('');
for(let i=0;i<42;i++){const d=new Date(Date.UTC(y,m-1,1-off+i)),ds=d.toISOString().slice(0,10),r=recs.find(x=>x.workDate===ds);const cls=['day',d.getUTCMonth()!==m-1&&'o',ds===today&&'t',r&&(r.status==='work'?(r.lateIntervals||r.earlyIntervals?'l':'w'):r.status==='unpaid'?'u':'v')].filter(Boolean).join(' ');
h+=`<div class="${cls}" data-d="${ds}"><b>${d.getUTCDate()}</b>${r?`<br>${r.status==='work'?hr(r.totalSec)+'h':'nghỉ'}<br>${money(r.expectedTotal)}${r.lateIntervals||r.earlyIntervals?' ⏰':''}`:''}</div>`}
$('#grid').innerHTML=h}
function renderPay(){const R=monthRecs(),w=R.filter(r=>r.status==='work'),sum=k=>R.reduce((a,r)=>a+(r[k]||0),0),exp=sum('expectedTotal'),P=pays.filter(p=>p.payrollMonth===ym),got=P.reduce((a,p)=>a+p.amount,0),diff=got-exp;
const msg=diff<0?'Tiền thực nhận thấp hơn lương dự kiến':diff>0?'Tiền thực nhận cao hơn lương dự kiến':'Đã khớp';
$('#stats').innerHTML=[['Lương dự kiến',money(exp)],['Thực nhận',money(got)],['Chênh lệch',money(diff)+' – '+msg],['Số ngày làm',w.length],['Giờ làm',hr(sum('totalSec'))],['Giờ thường',hr(sum('regularSec'))],['Giờ tăng ca',hr(sum('overtimeSec'))],['Tiền tăng ca',money(sum('overtimePay'))],['Khấu trừ trễ/về sớm',money(sum('latePenalty')+sum('earlyPenalty'))+' ('+Math.round(sum('latePenaltyMinutes')+sum('earlyPenaltyMinutes'))+' phút)']].map(([a,b])=>`<div>${a}<b>${b}</b></div>`).join('');
$('#tbl').innerHTML='<tr><th>Ngày<th>Ca<th>Công<th>Trễ(phút)<th>Mốc trễ<th>Về sớm(phút)<th>TC(giờ)<th>Lương ca<th>Tiền TC<th>Trừ trễ<th>Trừ sớm<th>Tổng</tr>'+R.map(r=>{const shift=r.shiftHours?`${r.shiftHours}h`:r.start?`${r.start}–${r.end||''}`:'—',work=r.halfDay?'Nửa ngày':r.shiftHours?'Đủ ca':'—',late=r.lateMinutes??Math.round((r.lateSec||0)/60),early=Math.round((r.earlySec||0)/60),ot=r.overtimeHours??((r.overtimeSec||0)/3600);return`<tr data-d="${r.workDate}"><td>${r.workDate.slice(8)}<td>${shift}<td>${work}<td>${late}<td>${r.lateIntervals||0}<td>${early}<td>${(+ot).toFixed(2)}<td>${money(r.basePay)}<td>${money(r.overtimePay)}<td>${money(r.latePenalty)}<td>${money(r.earlyPenalty)}<td>${money(r.expectedTotal)}</tr>`}).join('');
$('#ptbl').innerHTML=P.map(p=>`<tr><td>${p.paymentDate}<td>${esc(p.type)} ${esc(p.note)}<td>${money(p.amount)}<td><button class="d np" data-pd="${p.id}">Xóa</button></tr>`).join('')||'<tr><td>Chưa có khoản nào</tr>'}
function renderYear(){
  $('#yearInput').value=year;
  const months=Array.from({length:12},(_,i)=>{
    const month=String(i+1).padStart(2,'0'),key=`${year}-${month}`,R=recs.filter(r=>r.workDate.startsWith(key)),P=pays.filter(p=>p.payrollMonth===key);
    const sum=k=>R.reduce((a,r)=>a+(Number(r[k])||0),0),work=R.filter(r=>r.status==='work'),days=work.reduce((a,r)=>a+(r.halfDay?0.5:1),0),hours=sum('totalSec')/3600,overtime=sum('overtimeSec')/3600;
    return{key,month:i+1,records:R.length,days,hours,overtime,average:days?hours/days:0,expected:sum('expectedTotal'),received:P.reduce((a,p)=>a+(Number(p.amount)||0),0)};
  });
  const records=months.reduce((a,m)=>a+m.records,0),totalHours=months.reduce((a,m)=>a+m.hours,0),totalOvertime=months.reduce((a,m)=>a+m.overtime,0),totalDays=months.reduce((a,m)=>a+m.days,0),totalExpected=months.reduce((a,m)=>a+m.expected,0),totalReceived=months.reduce((a,m)=>a+m.received,0),active=months.filter(m=>m.records);
  const extrema=fn=>{if(!active.length)return'—';const value=fn(active[0]);return active.filter(m=>fn(m)===value).map(m=>`T${m.month}`).join(', ')};
  $('#yearStats').innerHTML=[
    ['Tổng lương dự kiến',money(totalExpected)],['Tổng thực nhận',money(totalReceived)],['Số ngày làm quy đổi',`${totalDays.toLocaleString('vi-VN')} công`],
    ['Tổng giờ làm',`${totalHours.toFixed(2)} giờ`],['Tổng giờ tăng ca',`${totalOvertime.toFixed(2)} giờ`],['Giờ làm TB/tháng',`${(totalHours/12).toFixed(2)} giờ`],
    ['Tháng nhiều công nhất',extrema(m=>m.days)],['Tháng ít công nhất',extrema(m=>m.days)]
  ].map(([label,value],i)=>`<div>${label}<b>${value}</b>${i===5?'<small>Trung bình trên 12 tháng</small>':''}${i===6||i===7?'<small>Trong các tháng có chấm công</small>':''}</div>`).join('');
  const max=Math.max(0,...months.flatMap(m=>[m.expected,m.received])),min=Math.min(0,...months.flatMap(m=>[m.expected,m.received])),spread=max-min,range=spread||1,chartW=960,chartH=300,top=22,bottom=42,left=58,right=12,plotH=chartH-top-bottom,plotW=chartW-left-right,barW=13,zeroY=top+plotH*max/range;
  const lines=Array.from({length:5},(_,i)=>{const y=top+plotH*i/4,value=max-spread*i/4;return`<line x1="${left}" y1="${y}" x2="${chartW-right}" y2="${y}" class="chart-grid"/><text x="${left-8}" y="${y+4}" text-anchor="end" class="chart-axis">${compactMoney(value)}</text>`}).join('');
  const bar=(x,value,kind,month)=>{const height=Math.abs(value)*plotH/range,y=value>=0?zeroY-height:zeroY;return`<rect x="${x}" y="${y}" width="${barW}" height="${height}" rx="2" class="${kind}"><title>T${month}: ${kind==='bar-expected'?'lương dự kiến':'thực nhận'} ${money(value)}</title></rect>`};
  const bars=months.map((m,i)=>{const center=left+plotW*(i+.5)/12;return`${bar(center-barW-2,m.expected,'bar-expected',m.month)}${bar(center+2,m.received,'bar-paid',m.month)}<text x="${center}" y="${chartH-14}" text-anchor="middle" class="chart-axis">T${m.month}</text>`}).join('');
  $('#yearChart').innerHTML=`<svg viewBox="0 0 ${chartW} ${chartH}" role="img" aria-label="Biểu đồ lương dự kiến và tiền thực nhận theo từng tháng năm ${year}">${lines}${bars}</svg>`;
  $('#yearTable').innerHTML='<tr><th>Tháng<th>Công<th>Giờ làm<th>Giờ TB/công<th>Tăng ca<th>Lương dự kiến<th>Thực nhận</tr>'+months.map(m=>`<tr><td>T${m.month}<td>${m.days.toLocaleString('vi-VN')}<td>${m.hours.toFixed(2)}<td>${m.average.toFixed(2)}<td>${m.overtime.toFixed(2)}<td>${money(m.expected)}<td>${money(m.received)}</tr>`).join('')+`<tr class="year-total"><th>Cả năm<th>${totalDays.toLocaleString('vi-VN')}<th>${totalHours.toFixed(2)}<th>${totalDays?(totalHours/totalDays).toFixed(2):'0.00'}<th>${totalOvertime.toFixed(2)}<th>${money(totalExpected)}<th>${money(totalReceived)}</tr>`;
}
function compactMoney(n){const sign=n<0?'-':'';n=Math.abs(n);if(n>=1000000)return`${sign}${(n/1000000).toLocaleString('vi-VN',{maximumFractionDigits:1})}tr`;if(n>=1000)return`${sign}${Math.round(n/1000)}k`;return`${sign}${Math.round(n)}`}
function conv(){const s=get('s_');$('#conv').textContent=s.payMode==='daily'?`${money(s.dailyRate/s.stdH)}/giờ · ca 13h ${money(s.dailyRate13)}/ngày`:money(s.hourlyRate)+'/giờ'}
function readM(){const r={...get('s_'),status:$('#m_status').value,shiftHours:+$('#m_shiftHours').value,lateEnabled:$('#m_lateEnabled').checked,lateMinutes:+$('#m_lateMinutes').value||0,halfDay:$('#m_halfDay').checked,overtimeHours:+$('#m_overtimeHours').value||0,note:$('#m_note').value};['allowance','bonus','otherDeduction','adjustment'].forEach(k=>r[k]=+$('#m_'+k).value||0);return r}
function prev(){const r=readM();if(r.status!=='work'){$('#pv').textContent='Tiền: '+money(r.status==='unpaid'?0:r.adjustment);return{r,res:{errors:[],expectedTotal:r.status==='unpaid'?0:r.adjustment}}}
const x=calc(r);$('#pv').innerHTML=x.errors.length?`<span class=err>${x.errors.join('<br>')}</span>`:`Ca ${x.shiftHours} tiếng${x.halfDay?' · nửa ngày':''} (tính lương thường ${hr(x.regularSec)}h, tăng ca ${hr(x.overtimeSec)}h)<br>Lương ca ${money(x.basePay)} · Tăng ca ${money(x.overtimePay)}<br>${x.lateMinutes?`Đi trễ ${x.lateMinutes} phút = ${x.lateIntervals} mốc, trừ ${money(x.latePenalty)}`:'Không đi trễ'}<br><b>Tổng: ${money(x.expectedTotal)}</b>`;return{r,res:x}}
function syncLateField(){$('#m_lateMinutes').disabled=!$('#m_lateEnabled').checked}
function openDay(d){cur=d;const r=recs.find(x=>x.workDate===d);$('#dt').textContent='Chấm công ngày '+d;const o=r||{...S,status:'work',shiftHours:8,lateEnabled:false,lateMinutes:0,halfDay:false,overtimeHours:0,allowance:0,bonus:0,otherDeduction:0,adjustment:0,note:''};$('#m_status').value=o.status;$('#m_shiftHours').value=o.shiftHours??(o.stdH===13?13:8);$('#m_lateEnabled').checked=o.shiftHours!=null?!!o.lateEnabled:!!o.lateSec;$('#m_lateMinutes').value=o.lateMinutes??Math.ceil((o.lateSec||0)/60);$('#m_halfDay').checked=!!o.halfDay;$('#m_overtimeHours').value=o.overtimeHours??((o.overtimeSec||0)/3600);syncLateField();['allowance','bonus','otherDeduction','adjustment'].forEach(k=>$('#m_'+k).value=o[k]||0);$('#m_note').value=o.note||'';$('#mdel').style.display=r?'':'none';prev();$('#dlg').showModal()}
$('#dlg').addEventListener('input',prev);$('#dlg').addEventListener('change',prev);$('#m_lateEnabled').addEventListener('change',syncLateField);$('#mclose').onclick=()=>$('#dlg').close();
$('#msave').onclick=async e=>{const{r,res}=prev();if(res.errors.length)return toast('Dữ liệu không hợp lệ');e.target.disabled=true;try{await put('attendance',{...r,...res,id:cur,workDate:cur,updatedAt:Date.now()});await load();$('#dlg').close();toast('Đã lưu')}catch(x){toast('Lỗi lưu: '+x.message)}e.target.disabled=false};
$('#mdel').onclick=async()=>{if(confirm('Xóa chấm công ngày '+cur+'?')){await del('attendance',cur);await load();$('#dlg').close()}};
document.addEventListener('click',async e=>{const d=e.target.closest('[data-d]');if(d)openDay(d.dataset.d);if(e.target.dataset.pd&&confirm('Xóa khoản này?')){await del('payments',e.target.dataset.pd);load()}});
const shift=n=>{const[y,m]=ym.split('-').map(Number),d=new Date(Date.UTC(y,m-1+n,1));ym=d.toISOString().slice(0,7);render()};
$('#prev').onclick=()=>shift(-1);$('#next').onclick=()=>shift(1);$('#cur').onclick=()=>{ym=today.slice(0,7);render()};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('on',x===b));document.querySelectorAll('.sec').forEach(s=>s.hidden=s.id!==b.dataset.t)});
$('#yearInput').onchange=e=>{const next=Number(e.target.value);if(!Number.isInteger(next)||next<2000||next>9999){toast('Năm phải từ 2000 đến 9999');e.target.value=year;return}year=next;renderYear()};
$('#sf').addEventListener('input',conv);
$('#ssave').onclick=async()=>{const s=get('s_');if(!(s.stdH>0&&s.interval>0))return toast('Giờ công và mốc đi trễ phải > 0');S={...s,id:'default'};await put('settings',S);toast('Đã lưu mặc định (không ảnh hưởng ngày cũ)')};
$('#padd').onclick=async()=>{const a=+$('#pa').value,d=$('#pd').value;if(!d||!a)return toast('Nhập ngày và số tiền');await put('payments',{id:crypto.randomUUID(),paymentDate:d,payrollMonth:ym,amount:a,type:$('#pt').value,note:$('#pn').value,createdAt:Date.now()});$('#pa').value='';await load();toast('Đã thêm')};
const dl=(name,txt,mime)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type:mime}));a.download=name;a.click()};
$('#exp').onclick=async()=>dl(`workpay-${today}.json`,JSON.stringify({app:'workpay',version:1,attendance:await all('attendance'),payments:await all('payments'),settings:await all('settings')},null,1),'application/json');
$('#csv').onclick=()=>{const h=['Ngày','Trạng thái','Ca','Công','Phút trễ','Mốc trễ','Giờ tăng ca','Lương ca','Tiền tăng ca','Trừ trễ','Trừ về sớm','Phụ cấp','Thưởng','Khấu trừ khác','Điều chỉnh','Tổng'];dl(`luong-${ym}.csv`,'\ufeff'+[h,...monthRecs().map(r=>[r.workDate,r.status,r.shiftHours??'',r.halfDay?'Nửa ngày':'Đủ ca',r.lateMinutes??Math.round((r.lateSec||0)/60),r.lateIntervals||0,r.overtimeHours??((r.overtimeSec||0)/3600),r.basePay,r.overtimePay,r.latePenalty,r.earlyPenalty,r.allowance,r.bonus,r.otherDeduction,r.adjustment,r.expectedTotal])].map(l=>l.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\r\n'),'text/csv')};
$('#imp').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(d.app!=='workpay'||d.version!==1||!Array.isArray(d.attendance)||!Array.isArray(d.payments))throw Error('Sai định dạng/phiên bản');const rep=$('#imode').value==='replace';if(!confirm(`Nhập ${d.attendance.length} chấm công, ${d.payments.length} thanh toán (${rep?'THAY THẾ toàn bộ dữ liệu hiện có':'hợp nhất'})?`))return;await bulk(d,rep);await load();toast('Đã nhập')}catch(x){toast('Lỗi nhập: '+x.message)}e.target.value=''};
$('#wipe').onclick=async()=>{if(confirm('Xóa TOÀN BỘ dữ liệu? Không thể hoàn tác.')&&confirm('Xác nhận lần cuối: bạn đã xuất sao lưu chưa?')){await bulk({},true);await load()}};
await load();
